[versions]
baksmali = "b6365a84f4" # https://github.com/google/smali/issues/100
commons_io = "2.21.0"
commons_cli = "1.11.0"
commons_lang3 = "3.20.0"
commons_text = "1.15.0"
guava = "33.5.0-jre"
junit = "4.13.2"
r8 = "8.13.19"
smali = "b6365a84f4" # https://github.com/google/smali/issues/100
xmlpull = "1.1.3.1"
xmlunit = "2.11.0"

[libraries]
baksmali = { module = "com.github.iBotPeaches.smali:smali-baksmali", version.ref = "baksmali" }
commons_cli = { module = "commons-cli:commons-cli", version.ref = "commons_cli"}
commons_io = { module = "commons-io:commons-io", version.ref = "commons_io" }
commons_lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons_lang3" }
commons_text = { module = "org.apache.commons:commons-text", version.ref = "commons_text" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { module = "junit:junit", version.ref = "junit" }
r8 = { module = "com.android.tools:r8", version.ref = "r8" }
smali = { module = "com.github.iBotPeaches.smali:smali", version.ref = "smali" }
xmlpull = { module = "xmlpull:xmlpull", version.ref = "xmlpull" }
xmlunit = { module = "org.xmlunit:xmlunit-legacy", version.ref = "xmlunit" }
