[versions]
baksmali = "3.0.3"
commons_io = "2.15.1"
commons_cli = "1.6.0"
commons_lang3 = "3.14.0"
commons_text = "1.11.0"
guava = "32.0.1-jre"
junit = "4.13.2"
proguard = "7.4.1"
shadow = "8.1.1"
smali = "3.0.3"
xmlpull = "1.1.4c"
xmlunit = "2.9.1"

[libraries]
baksmali = { module = "com.android.tools.smali:smali-baksmali", version.ref = "baksmali" }
commons_cli = { module = "commons-cli:commons-cli", version.ref = "commons_cli"}
commons_io = { module = "commons-io:commons-io", version.ref = "commons_io" }
commons_lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons_lang3" }
commons_text = { module = "org.apache.commons:commons-text", version.ref = "commons_text" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { module = "junit:junit", version.ref = "junit" }
proguard = { module = "com.guardsquare:proguard-gradle", version.ref = "proguard" }
smali = { module = "com.android.tools.smali:smali", version.ref = "smali" }
xmlpull = { module = "xpp3:xpp3", version.ref = "xmlpull" }
xmlunit = { module = "org.xmlunit:xmlunit-legacy", version.ref = "xmlunit" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
